// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBULm4pg68PHbEBDJcasK6WPesngsRJsuA',
    appId: '1:313410943283:web:1698dff6bf3cfdb2b96646',
    messagingSenderId: '313410943283',
    projectId: 'reserve-e086b',
    authDomain: 'reserve-e086b.firebaseapp.com',
    storageBucket: 'reserve-e086b.firebasestorage.app',
    measurementId: 'G-W044YZB99F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZSCE7xzklfcvQ7dPuEqpj-a3jyH-csB8',
    appId: '1:313410943283:android:72dfdf7ecfb4d786b96646',
    messagingSenderId: '313410943283',
    projectId: 'reserve-e086b',
    storageBucket: 'reserve-e086b.firebasestorage.app',
  );
}
